# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release workflow

on:
  push:
    branches: [ main ]

jobs:
  cleanup:
    runs-on: ubuntu-20.04
    steps: 
      - name: Delete drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    needs: cleanup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'yarn'
    
    - name: Cache Electron
      uses: actions/cache@v1
      with:
        path: ${HOME}/.cache/electron
        key: ${{ runner.os }}-electron-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-electron-cache-
    - name: Cache Electron-Builder
      uses: actions/cache@v1
      with:
        path: ${HOME}/.cache/electron-builder
        key: ${{ runner.os }}-electron-builder-cache-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-electron-builder-cache-
    - name: Install dependencies with Yarn
      run: yarn install
    - name: Build and release binaries
      run: yarn release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
